<?php

// Register Custom Post Type
function corporaciond1_custom_post_type() {

    $labels = array(
        'name'                  => _x( 'Clientes', 'Post Type General Name', 'corporaciond1' ),
        'singular_name'         => _x( 'Cliente', 'Post Type Singular Name', 'corporaciond1' ),
        'menu_name'             => __( 'Clientes', 'corporaciond1' ),
        'name_admin_bar'        => __( 'Clientes', 'corporaciond1' ),
        'archives'              => __( 'Archivo de Clientes', 'corporaciond1' ),
        'attributes'            => __( 'Atributos de Cliente', 'corporaciond1' ),
        'parent_item_colon'     => __( 'Cliente Padre:', 'corporaciond1' ),
        'all_items'             => __( 'Todos los Clientes', 'corporaciond1' ),
        'add_new_item'          => __( 'Agregar Nuevo Cliente', 'corporaciond1' ),
        'add_new'               => __( 'Agregar Nuevo', 'corporaciond1' ),
        'new_item'              => __( 'Nuevo Cliente', 'corporaciond1' ),
        'edit_item'             => __( 'Editar Cliente', 'corporaciond1' ),
        'update_item'           => __( 'Actualizar Cliente', 'corporaciond1' ),
        'view_item'             => __( 'Ver Cliente', 'corporaciond1' ),
        'view_items'            => __( 'Ver Clientes', 'corporaciond1' ),
        'search_items'          => __( 'Buscar Clientes', 'corporaciond1' ),
        'not_found'             => __( 'No hay resultados', 'corporaciond1' ),
        'not_found_in_trash'    => __( 'No hay resultados en Papelera', 'corporaciond1' ),
        'featured_image'        => __( 'Logo del Cliente', 'corporaciond1' ),
        'set_featured_image'    => __( 'Colocar Logo del Cliente', 'corporaciond1' ),
        'remove_featured_image' => __( 'Remover Logo del Cliente', 'corporaciond1' ),
        'use_featured_image'    => __( 'Usar como Logo del Cliente', 'corporaciond1' ),
        'insert_into_item'      => __( 'Insertar en Cliente', 'corporaciond1' ),
        'uploaded_to_this_item' => __( 'Cargado a este Cliente', 'corporaciond1' ),
        'items_list'            => __( 'Listado de Clientes', 'corporaciond1' ),
        'items_list_navigation' => __( 'Navegación del Listado de Clientes', 'corporaciond1' ),
        'filter_items_list'     => __( 'Filtro del Listado de Clientes', 'corporaciond1' ),
    );
    $args = array(
        'label'                 => __( 'Cliente', 'corporaciond1' ),
        'description'           => __( 'Casos de Éxito de D1', 'corporaciond1' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'taxonomies'            => array( 'tipo_clientes' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'menu_icon'             => 'dashicons-businessman',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => true,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'show_in_rest'          => true,
    );
    register_post_type( 'clientes', $args );

    $labels = array(
        'name'                  => _x( 'Servicios', 'Post Type General Name', 'corporaciond1' ),
        'singular_name'         => _x( 'Servicio', 'Post Type Singular Name', 'corporaciond1' ),
        'menu_name'             => __( 'Servicios', 'corporaciond1' ),
        'name_admin_bar'        => __( 'Servicios', 'corporaciond1' ),
        'archives'              => __( 'Archivo de Servicios', 'corporaciond1' ),
        'attributes'            => __( 'Atributos de Servicio', 'corporaciond1' ),
        'parent_item_colon'     => __( 'Servicio Padre:', 'corporaciond1' ),
        'all_items'             => __( 'Todos los Servicios', 'corporaciond1' ),
        'add_new_item'          => __( 'Agregar Nuevo Servicio', 'corporaciond1' ),
        'add_new'               => __( 'Agregar Nuevo', 'corporaciond1' ),
        'new_item'              => __( 'Nuevo Servicio', 'corporaciond1' ),
        'edit_item'             => __( 'Editar Servicio', 'corporaciond1' ),
        'update_item'           => __( 'Actualizar Servicio', 'corporaciond1' ),
        'view_item'             => __( 'Ver Servicio', 'corporaciond1' ),
        'view_items'            => __( 'Ver Servicios', 'corporaciond1' ),
        'search_items'          => __( 'Buscar Servicios', 'corporaciond1' ),
        'not_found'             => __( 'No hay resultados', 'corporaciond1' ),
        'not_found_in_trash'    => __( 'No hay resultados en Papelera', 'corporaciond1' ),
        'featured_image'        => __( 'Logo del Servicio', 'corporaciond1' ),
        'set_featured_image'    => __( 'Colocar Logo del Servicio', 'corporaciond1' ),
        'remove_featured_image' => __( 'Remover Logo del Servicio', 'corporaciond1' ),
        'use_featured_image'    => __( 'Usar como Logo del Servicio', 'corporaciond1' ),
        'insert_into_item'      => __( 'Insertar en Servicio', 'corporaciond1' ),
        'uploaded_to_this_item' => __( 'Cargado a este Servicio', 'corporaciond1' ),
        'items_list'            => __( 'Listado de Servicios', 'corporaciond1' ),
        'items_list_navigation' => __( 'Navegación del Listado de Servicios', 'corporaciond1' ),
        'filter_items_list'     => __( 'Filtro del Listado de Servicios', 'corporaciond1' ),
    );
    $args = array(
        'label'                 => __( 'Servicio', 'corporaciond1' ),
        'description'           => __( 'Servicios que ofrecemos', 'corporaciond1' ),
        'labels'                => $labels,
        'supports'              => array( 'title', 'editor', 'thumbnail' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'menu_icon'             => 'dashicons-image-filter',
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => true,
        'publicly_queryable'    => true,
        'capability_type'       => 'page',
        'show_in_rest'          => true,
    );
    register_post_type( 'servicios', $args );


    // Register Custom Taxonomy
    $labels = array(
        'name'                       => _x( 'Tipos de Cliente', 'Taxonomy General Name', 'corporaciond1' ),
        'singular_name'              => _x( 'Tipo de Cliente', 'Taxonomy Singular Name', 'corporaciond1' ),
        'menu_name'                  => __( 'Tipos de Cliente', 'corporaciond1' ),
        'all_items'                  => __( 'Todos los Tipos', 'corporaciond1' ),
        'parent_item'                => __( 'Tipo Padre', 'corporaciond1' ),
        'parent_item_colon'          => __( 'Tipo Padre:', 'corporaciond1' ),
        'new_item_name'              => __( 'Nuevo Tipo de Cliente', 'corporaciond1' ),
        'add_new_item'               => __( 'Agregar Tipo de Cliente', 'corporaciond1' ),
        'edit_item'                  => __( 'Editar Tipo de Cliente', 'corporaciond1' ),
        'update_item'                => __( 'Actualizar Tipo de Cliente', 'corporaciond1' ),
        'view_item'                  => __( 'Ver Tipo de Cliente', 'corporaciond1' ),
        'separate_items_with_commas' => __( 'Separar tipos por comas', 'corporaciond1' ),
        'add_or_remove_items'        => __( 'Agregar o Remover Tipos', 'corporaciond1' ),
        'choose_from_most_used'      => __( 'Escoger de los más Usados', 'corporaciond1' ),
        'popular_items'              => __( 'Tipos Populares', 'corporaciond1' ),
        'search_items'               => __( 'Buscar Tipos', 'corporaciond1' ),
        'not_found'                  => __( 'No hay resultados', 'corporaciond1' ),
        'no_terms'                   => __( 'No hay Tipos', 'corporaciond1' ),
        'items_list'                 => __( 'Listado de Tipos de Cliente', 'corporaciond1' ),
        'items_list_navigation'      => __( 'Navegación del Listado de Tipos de Cliente', 'corporaciond1' ),
    );
    $args = array(
        'labels'                     => $labels,
        'hierarchical'               => true,
        'public'                     => true,
        'show_ui'                    => true,
        'show_admin_column'          => true,
        'show_in_nav_menus'          => true,
        'show_tagcloud'              => true,
        'show_in_rest'               => true,
    );
    register_taxonomy( 'tipo_clientes', array( 'clientes' ), $args );


}
add_action( 'init', 'corporaciond1_custom_post_type', 0 );
